package com.clinic.notification.service;

import com.clinic.notification.domain.*;import com.clinic.notification.dto.NotificationDtos.EventRequest;import com.clinic.notification.repository.*;import com.fasterxml.jackson.databind.*;import com.fasterxml.jackson.databind.node.ObjectNode;import org.springframework.beans.factory.annotation.Value;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.util.UriComponentsBuilder;
import java.net.URI;import java.net.http.*;import java.time.*;import java.util.*;

@Service public class GoogleCalendarService{
 private final CredentialRepository credentials;private final StateRepository states;private final CalendarLinkRepository links;private final ObjectMapper mapper;private final HttpClient http=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(3)).build();
 private final String clientId,clientSecret,redirectUri,frontendSuccess;
 public GoogleCalendarService(CredentialRepository c,StateRepository s,CalendarLinkRepository l,ObjectMapper mapper,@Value("${google.client-id:}")String id,@Value("${google.client-secret:}")String secret,@Value("${google.redirect-uri}")String redirect,@Value("${google.frontend-success-uri}")String success){credentials=c;states=s;links=l;this.mapper=mapper;clientId=id;clientSecret=secret;redirectUri=redirect;frontendSuccess=success;}
 @Transactional public String authorizationUrl(UUID userId,String email){if(clientId.isBlank())throw new IllegalStateException("Google Calendar OAuth is not configured");OAuthState state=states.save(new OAuthState(userId,email));return UriComponentsBuilder.fromUriString("https://accounts.google.com/o/oauth2/v2/auth").queryParam("client_id",clientId).queryParam("redirect_uri",redirectUri).queryParam("response_type","code").queryParam("scope","https://www.googleapis.com/auth/calendar.events").queryParam("access_type","offline").queryParam("prompt","consent").queryParam("state",state.getId()).build().encode().toUriString();}
 @Transactional public String callback(UUID stateId,String code){OAuthState state=states.findById(stateId).orElseThrow(()->new IllegalArgumentException("Invalid OAuth state"));if(state.expired())throw new IllegalArgumentException("OAuth state expired");JsonNode token=token(Map.of("code",code,"client_id",clientId,"client_secret",clientSecret,"redirect_uri",redirectUri,"grant_type","authorization_code"));String access=token.path("access_token").asText();String refresh=token.path("refresh_token").asText();long expires=token.path("expires_in").asLong(3600);credentials.save(new OAuthCredential(state.getUserId(),state.getEmail(),access,refresh,Instant.now().plusSeconds(expires-30)));states.delete(state);return frontendSuccess;}
 public boolean connected(UUID userId){return credentials.existsById(userId);}
 @Transactional public void process(String action,UUID userId,UUID appointmentId,EventRequest e){OAuthCredential credential=validCredential(userId);switch(action){case"CREATE"->create(credential,appointmentId,e);case"UPDATE"->update(credential,appointmentId,e);case"DELETE"->delete(credential,appointmentId);default->throw new IllegalArgumentException("Unknown calendar action");}}
 private OAuthCredential validCredential(UUID userId){OAuthCredential c=credentials.findById(userId).orElseThrow(()->new IllegalStateException("Calendar not connected for user"));if(Instant.now().isAfter(c.getExpiresAt())){if(c.getRefreshToken()==null||c.getRefreshToken().isBlank())throw new IllegalStateException("Calendar authorization expired");JsonNode token=token(Map.of("refresh_token",c.getRefreshToken(),"client_id",clientId,"client_secret",clientSecret,"grant_type","refresh_token"));c.refresh(token.path("access_token").asText(),Instant.now().plusSeconds(token.path("expires_in").asLong(3600)-30));}return c;}
 private void create(OAuthCredential c,UUID appointmentId,EventRequest e){JsonNode response=request("POST","https://www.googleapis.com/calendar/v3/calendars/primary/events",c.getAccessToken(),eventBody(e));String eventId=response.path("id").asText();if(eventId.isBlank())throw new IllegalStateException("Google did not return event id");links.findByUserIdAndAppointmentId(c.getUserId(),appointmentId).orElseGet(()->links.save(new CalendarLink(c.getUserId(),appointmentId,eventId)));}
 private void update(OAuthCredential c,UUID appointmentId,EventRequest e){CalendarLink link=links.findByUserIdAndAppointmentId(c.getUserId(),appointmentId).orElse(null);if(link==null){create(c,appointmentId,e);return;}request("PUT","https://www.googleapis.com/calendar/v3/calendars/primary/events/"+link.getEventId(),c.getAccessToken(),eventBody(e));}
 private void delete(OAuthCredential c,UUID appointmentId){CalendarLink link=links.findByUserIdAndAppointmentId(c.getUserId(),appointmentId).orElse(null);if(link==null)return;request("DELETE","https://www.googleapis.com/calendar/v3/calendars/primary/events/"+link.getEventId(),c.getAccessToken(),null);links.deleteByUserIdAndAppointmentId(c.getUserId(),appointmentId);}
 private ObjectNode eventBody(EventRequest e){ObjectNode body=mapper.createObjectNode();body.put("summary","Clinic appointment with "+e.doctorName());body.put("description",e.message());body.putObject("start").put("dateTime",e.startAt().toString());body.putObject("end").put("dateTime",e.startAt().plusMinutes(e.durationMinutes()).toString());return body;}
 private JsonNode request(String method,String url,String access,JsonNode body){try{HttpRequest.Builder b=HttpRequest.newBuilder(URI.create(url)).timeout(Duration.ofSeconds(12)).header("Authorization","Bearer "+access).header("Content-Type","application/json");if("DELETE".equals(method))b.DELETE();else b.method(method,HttpRequest.BodyPublishers.ofString(mapper.writeValueAsString(body)));HttpResponse<String> r=http.send(b.build(),HttpResponse.BodyHandlers.ofString());if(r.statusCode()/100!=2)throw new IllegalStateException("Google Calendar HTTP "+r.statusCode());return r.body().isBlank()?mapper.createObjectNode():mapper.readTree(r.body());}catch(Exception x){if(x instanceof InterruptedException)Thread.currentThread().interrupt();throw new IllegalStateException("Google Calendar request failed",x);}}
 private JsonNode token(Map<String,String> form){try{String body=form.entrySet().stream().map(e->java.net.URLEncoder.encode(e.getKey(),java.nio.charset.StandardCharsets.UTF_8)+"="+java.net.URLEncoder.encode(e.getValue(),java.nio.charset.StandardCharsets.UTF_8)).collect(java.util.stream.Collectors.joining("&"));HttpRequest r=HttpRequest.newBuilder(URI.create("https://oauth2.googleapis.com/token")).timeout(Duration.ofSeconds(12)).header("Content-Type","application/x-www-form-urlencoded").POST(HttpRequest.BodyPublishers.ofString(body)).build();HttpResponse<String> response=http.send(r,HttpResponse.BodyHandlers.ofString());if(response.statusCode()/100!=2)throw new IllegalStateException("Google OAuth HTTP "+response.statusCode());return mapper.readTree(response.body());}catch(Exception x){if(x instanceof InterruptedException)Thread.currentThread().interrupt();throw new IllegalStateException("Google OAuth exchange failed",x);}}
}
