package com.clinic.appointment.controller;
import com.clinic.appointment.dto.AppointmentDtos.*;import com.clinic.appointment.service.AppointmentService;import jakarta.validation.Valid;import org.springframework.http.HttpStatus;import org.springframework.web.bind.annotation.*;import java.time.LocalDate;import java.util.*;
@RestController public class AppointmentController{private final AppointmentService service;public AppointmentController(AppointmentService s){service=s;}
 @PostMapping("/api/appointments/holds")@ResponseStatus(HttpStatus.CREATED)HoldResponse hold(@RequestHeader("X-User-Id")UUID user,@RequestHeader("X-User-Role")String role,@Valid@RequestBody HoldRequest r){patient(role);return service.hold(user,r);}
 @PostMapping("/api/appointments")@ResponseStatus(HttpStatus.CREATED)AppointmentResponse book(@RequestHeader("X-User-Id")UUID user,@RequestHeader("X-User-Email")String email,@RequestHeader("X-User-Role")String role,@Valid@RequestBody BookingRequest r){patient(role);return service.book(user,email,r);}
 @GetMapping("/api/appointments")List<AppointmentResponse> list(@RequestHeader("X-User-Id")UUID user,@RequestHeader("X-User-Role")String role){return service.list(user,role);}
 @GetMapping("/api/appointments/{id}")AppointmentResponse get(@PathVariable UUID id,@RequestHeader("X-User-Id")UUID user,@RequestHeader("X-User-Role")String role){return service.get(id,user,role);}
 @DeleteMapping("/api/appointments/{id}")AppointmentResponse cancel(@PathVariable UUID id,@RequestHeader("X-User-Id")UUID user,@RequestHeader("X-User-Role")String role,@RequestParam(required=false)String reason){return service.cancel(id,user,role,reason);}
 @PutMapping("/api/appointments/{id}/reschedule")AppointmentResponse reschedule(@PathVariable UUID id,@RequestHeader("X-User-Id")UUID user,@RequestHeader("X-User-Role")String role,@Valid@RequestBody RescheduleRequest r){return service.reschedule(id,user,role,r);}
 @PostMapping("/api/appointments/{id}/post-visit")AppointmentResponse post(@PathVariable UUID id,@RequestHeader("X-User-Id")UUID user,@RequestHeader("X-User-Role")String role,@Valid@RequestBody PostVisitRequest r){doctor(role);return service.postVisit(id,user,r);}
 @GetMapping("/api/appointments/available-slots")List<SlotResponse> available(@RequestParam UUID doctorId,@RequestParam LocalDate date){return service.availability(doctorId,date);}
 private void patient(String r){if(!"PATIENT".equals(r))throw new SecurityException("Patient access required");}private void doctor(String r){if(!"DOCTOR".equals(r))throw new SecurityException("Doctor access required");}}
