package com.clinic.appointment.domain;
import jakarta.persistence.*;import java.time.*;import java.util.UUID;
@Entity @Table(name="appointments") public class Appointment{
 public enum Status{CONFIRMED,CANCELLED,COMPLETED}
 @Id private UUID id;@Column(nullable=false)private UUID patientId;@Column(nullable=false)private String patientName;@Column(nullable=false)private String patientEmail;
 @Column(nullable=false)private UUID doctorId;@Column(nullable=false)private UUID doctorUserId;@Column(nullable=false)private String doctorName;@Column(nullable=false)private String doctorEmail;
 @Column(nullable=false)private OffsetDateTime startAt;@Column(nullable=false)private int durationMinutes;@Enumerated(EnumType.STRING)@Column(nullable=false)private Status status;
 @Column(nullable=false,columnDefinition="text")private String symptoms;@Column(columnDefinition="text")private String preVisitSummary;private String urgencyLevel;
 @Column(columnDefinition="text")private String clinicalNotes;@Column(columnDefinition="text")private String prescriptionText;@Column(columnDefinition="text")private String postVisitSummary;
 @Column(nullable=false)private boolean reminderQueued;private String cancellationReason;@Column(nullable=false,updatable=false)private Instant createdAt;@Column(nullable=false)private Instant updatedAt;@Version private long version;
 protected Appointment(){}public Appointment(UUID patientId,String patientName,String patientEmail,UUID doctorId,UUID doctorUserId,String doctorName,String doctorEmail,OffsetDateTime startAt,int duration,String symptoms,String pre,String urgency){id=UUID.randomUUID();this.patientId=patientId;this.patientName=patientName;this.patientEmail=patientEmail;this.doctorId=doctorId;this.doctorUserId=doctorUserId;this.doctorName=doctorName;this.doctorEmail=doctorEmail;this.startAt=startAt;durationMinutes=duration;this.symptoms=symptoms;preVisitSummary=pre;urgencyLevel=urgency;status=Status.CONFIRMED;reminderQueued=false;createdAt=Instant.now();updatedAt=createdAt;}
 public void cancel(String reason){status=Status.CANCELLED;cancellationReason=reason;updatedAt=Instant.now();}public void reschedule(OffsetDateTime at,int duration){startAt=at;durationMinutes=duration;reminderQueued=false;updatedAt=Instant.now();}public void complete(String notes,String prescription,String summary){clinicalNotes=notes;prescriptionText=prescription;postVisitSummary=summary;status=Status.COMPLETED;updatedAt=Instant.now();}public void reminderQueued(){reminderQueued=true;updatedAt=Instant.now();}
 public UUID getId(){return id;}public UUID getPatientId(){return patientId;}public String getPatientName(){return patientName;}public String getPatientEmail(){return patientEmail;}public UUID getDoctorId(){return doctorId;}public UUID getDoctorUserId(){return doctorUserId;}public String getDoctorName(){return doctorName;}public String getDoctorEmail(){return doctorEmail;}public OffsetDateTime getStartAt(){return startAt;}public int getDurationMinutes(){return durationMinutes;}public Status getStatus(){return status;}public String getSymptoms(){return symptoms;}public String getPreVisitSummary(){return preVisitSummary;}public String getUrgencyLevel(){return urgencyLevel;}public String getClinicalNotes(){return clinicalNotes;}public String getPrescriptionText(){return prescriptionText;}public String getPostVisitSummary(){return postVisitSummary;}public String getCancellationReason(){return cancellationReason;}
}
