package com.clinic.appointment.service;

import com.clinic.appointment.client.*;import com.clinic.appointment.domain.*;import com.clinic.appointment.dto.AppointmentDtos.*;import com.clinic.appointment.repository.*;import com.fasterxml.jackson.databind.ObjectMapper;import org.springframework.beans.factory.annotation.Value;import org.springframework.dao.DataIntegrityViolationException;import org.springframework.scheduling.annotation.Scheduled;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;

@Service public class AppointmentService{
 private final AppointmentRepository appointments;private final SlotReservationRepository slots;private final PrescriptionItemRepository prescriptions;private final DoctorClient doctors;private final AiClient ai;private final OutboxPublisher outbox;private final ObjectMapper mapper;private final ZoneId clinicZone;
 public AppointmentService(AppointmentRepository a,SlotReservationRepository s,PrescriptionItemRepository p,DoctorClient d,AiClient ai,OutboxPublisher o,ObjectMapper mapper,@Value("${app.clinic-zone:Asia/Kolkata}")String zone){appointments=a;slots=s;prescriptions=p;doctors=d;this.ai=ai;outbox=o;this.mapper=mapper;clinicZone=ZoneId.of(zone);}
 @Transactional public HoldResponse hold(UUID patientId,HoldRequest r){DoctorClient.Availability availability=doctors.availability(r.doctorId(),r.startAt());if(availability==null||!availability.available())throw new SlotConflictException(availability==null?"Doctor availability unavailable":availability.reason());slots.deleteExpired(Instant.now());UUID id=UUID.randomUUID(),token=UUID.randomUUID();Instant expires=Instant.now().plusSeconds(300);int inserted=slots.tryInsert(id,r.doctorId(),r.startAt(),patientId,token,expires);if(inserted==0)throw new SlotConflictException("Slot is already booked or temporarily held");return new HoldResponse(token,expires);}
 @Transactional public AppointmentResponse book(UUID patientId,String patientEmail,BookingRequest r){SlotReservation hold=lockedHold(r.holdToken(),patientId);DoctorClient.Availability d=doctors.availability(hold.getDoctorId(),hold.getStartAt());if(d==null||!d.available())throw new SlotConflictException(d==null?"Doctor availability unavailable":d.reason());AiClient.PreSummary summary=ai.pre(r.symptoms());String summaryJson=json(summary);Appointment a=appointments.save(new Appointment(patientId,r.patientName(),patientEmail,d.doctorId(),d.doctorUserId(),d.doctorName(),d.doctorEmail(),hold.getStartAt(),d.slotDurationMinutes(),r.symptoms(),summaryJson,summary.urgencyLevel()));hold.confirm(a.getId());outbox.appointmentEvent(a,"BOOKING_CONFIRMED","Your appointment is confirmed.");return view(a);}
 public List<AppointmentResponse> list(UUID userId,String role){List<Appointment> found=switch(role){case"PATIENT"->appointments.findByPatientIdOrderByStartAtDesc(userId);case"DOCTOR"->appointments.findByDoctorUserIdOrderByStartAtDesc(userId);case"ADMIN"->appointments.findAllByOrderByStartAtDesc();default->throw new SecurityException("Unknown role");};return found.stream().map(this::view).toList();}
 public AppointmentResponse get(UUID id,UUID user,String role){Appointment a=entity(id);authorize(a,user,role);return view(a);}
 @Transactional public AppointmentResponse cancel(UUID id,UUID user,String role,String reason){Appointment a=entity(id);authorize(a,user,role);if(a.getStatus()!=Appointment.Status.CONFIRMED)throw new IllegalArgumentException("Only confirmed appointments can be cancelled");if(a.getStartAt().isBefore(OffsetDateTime.now()))throw new IllegalArgumentException("Past appointments cannot be cancelled");a.cancel(reason==null||reason.isBlank()?"Cancelled by user":reason);slots.deleteByAppointmentId(a.getId());outbox.appointmentEvent(a,"APPOINTMENT_CANCELLED","Appointment cancelled: "+a.getCancellationReason());return view(a);}
 @Transactional public AppointmentResponse reschedule(UUID id,UUID user,String role,RescheduleRequest r){Appointment a=entity(id);authorize(a,user,role);if(a.getStatus()!=Appointment.Status.CONFIRMED)throw new IllegalArgumentException("Only confirmed appointments can be rescheduled");SlotReservation hold=lockedHold(r.holdToken(),a.getPatientId());if(!hold.getDoctorId().equals(a.getDoctorId()))throw new IllegalArgumentException("Rescheduling to another doctor requires a new appointment");DoctorClient.Availability d=doctors.availability(hold.getDoctorId(),hold.getStartAt());if(d==null||!d.available())throw new SlotConflictException(d==null?"Doctor availability unavailable":d.reason());slots.deleteByAppointmentId(a.getId());a.reschedule(hold.getStartAt(),d.slotDurationMinutes());hold.confirm(a.getId());outbox.appointmentEvent(a,"APPOINTMENT_RESCHEDULED","Your appointment has been rescheduled.");return view(a);}
 @Transactional public AppointmentResponse postVisit(UUID id,UUID doctorUser,PostVisitRequest r){Appointment a=entity(id);if(!a.getDoctorUserId().equals(doctorUser))throw new SecurityException("This appointment belongs to another doctor");if(a.getStatus()!=Appointment.Status.CONFIRMED)throw new IllegalArgumentException("Appointment is not open for visit notes");String prescription=r.prescriptions().stream().map(p->p.medication()+" - "+p.instructions()+" (every "+p.intervalHours()+" hours for "+p.durationDays()+" days)").reduce((x,y)->x+"\n"+y).orElse("");AiClient.PostSummary summary=ai.post(r.clinicalNotes(),prescription);a.complete(r.clinicalNotes(),prescription,json(summary));int i=0;for(PrescriptionRequest p:r.prescriptions()){prescriptions.save(new PrescriptionItem(a.getId(),p.medication(),p.instructions(),p.intervalHours(),p.durationDays()));outbox.medication(a,p,i++);}outbox.appointmentEvent(a,"POST_VISIT_SUMMARY","Your post-visit summary and medication schedule are ready.");return view(a);}
 public List<SlotResponse> availability(UUID doctorId,LocalDate date){DoctorClient.DoctorProfile d=doctors.doctor(doctorId);if(d==null||!d.active())return List.of();OffsetDateTime from=date.atStartOfDay(clinicZone).toOffsetDateTime(),to=date.plusDays(1).atStartOfDay(clinicZone).toOffsetDateTime();Set<Instant> occupied=new HashSet<>(slots.occupied(doctorId,from,to,Instant.now()).stream().map(OffsetDateTime::toInstant).toList());List<SlotResponse> result=new ArrayList<>();for(LocalTime t=d.workingStart();!t.plusMinutes(d.slotDurationMinutes()).isAfter(d.workingEnd());t=t.plusMinutes(d.slotDurationMinutes())){OffsetDateTime at=ZonedDateTime.of(date,t,clinicZone).toOffsetDateTime();if(at.isAfter(OffsetDateTime.now()))result.add(new SlotResponse(at,!occupied.contains(at.toInstant())));}return result;}
 @Transactional public int doctorLeave(DoctorLeaveRequest r){OffsetDateTime from=r.date().atStartOfDay(clinicZone).toOffsetDateTime(),to=r.date().plusDays(1).atStartOfDay(clinicZone).toOffsetDateTime();List<Appointment> affected=appointments.findByDoctorIdAndStatusAndStartAtGreaterThanEqualAndStartAtLessThan(r.doctorId(),Appointment.Status.CONFIRMED,from,to);for(Appointment a:affected){a.cancel("Doctor leave: "+r.reason());slots.deleteByAppointmentId(a.getId());outbox.appointmentEvent(a,"DOCTOR_LEAVE_CANCELLED","The appointment was cancelled because "+r.doctorName()+" is unavailable. Please book another slot.");}return affected.size();}
 @Scheduled(fixedDelay=600000)@Transactional public void reminders(){OffsetDateTime now=OffsetDateTime.now(),until=now.plusHours(24);for(Appointment a:appointments.findByStatusAndReminderQueuedFalseAndStartAtBetween(Appointment.Status.CONFIRMED,now,until)){outbox.appointmentEvent(a,"APPOINTMENT_REMINDER","Reminder: your appointment is within 24 hours.");a.reminderQueued();}slots.deleteExpired(Instant.now());}
 private SlotReservation lockedHold(UUID token,UUID patient){SlotReservation h=slots.findByHoldToken(token).orElseThrow(()->new SlotConflictException("Hold not found"));if(!h.getPatientId().equals(patient))throw new SecurityException("Hold belongs to another patient");if(h.isConfirmed())throw new SlotConflictException("Hold has already been used");if(h.expired())throw new SlotConflictException("Hold expired; choose the slot again");return h;}
 private Appointment entity(UUID id){return appointments.findById(id).orElseThrow(()->new NoSuchElementException("Appointment not found"));}private void authorize(Appointment a,UUID user,String role){boolean ok="ADMIN".equals(role)||(a.getPatientId().equals(user)&&"PATIENT".equals(role))||(a.getDoctorUserId().equals(user)&&"DOCTOR".equals(role));if(!ok)throw new SecurityException("You cannot access this appointment");}
 private AppointmentResponse view(Appointment a){return new AppointmentResponse(a.getId(),a.getPatientId(),a.getPatientName(),a.getPatientEmail(),a.getDoctorId(),a.getDoctorUserId(),a.getDoctorName(),a.getDoctorEmail(),a.getStartAt(),a.getDurationMinutes(),a.getStatus(),a.getSymptoms(),a.getPreVisitSummary(),a.getUrgencyLevel(),a.getClinicalNotes(),a.getPrescriptionText(),a.getPostVisitSummary(),a.getCancellationReason());}
 private String json(Object value){try{return mapper.writeValueAsString(value);}catch(Exception e){throw new IllegalStateException("Could not serialize summary",e);}}
 public static class SlotConflictException extends RuntimeException{public SlotConflictException(String m){super(m);}}
}
