package com.clinic.appointment.service;
import com.clinic.appointment.domain.*;import com.clinic.appointment.dto.AppointmentDtos.PrescriptionRequest;import com.clinic.appointment.repository.OutboxEventRepository;import com.fasterxml.jackson.databind.ObjectMapper;import org.springframework.stereotype.Component;import java.time.*;import java.util.*;
@Component public class OutboxPublisher{private final OutboxEventRepository outbox;private final ObjectMapper mapper;public OutboxPublisher(OutboxEventRepository o,ObjectMapper m){outbox=o;mapper=m;}
 public void appointmentEvent(Appointment a,String type,String message){String key=a.getId()+":"+type+":"+a.getStartAt();if(outbox.existsByEventKey(key))return;EventPayload p=new EventPayload(key,type,a.getId(),a.getPatientId(),a.getPatientEmail(),a.getPatientName(),a.getDoctorUserId(),a.getDoctorEmail(),a.getDoctorName(),a.getStartAt(),a.getDurationMinutes(),message);save(key,"EVENT",p);}
 public void medication(Appointment a,PrescriptionRequest p,int index){String key=a.getId()+":MEDICATION:"+index;Instant start=Instant.now().plusSeconds(60);MedicationPayload payload=new MedicationPayload(key,a.getPatientId(),a.getPatientEmail(),a.getId(),p.medication(),p.instructions(),p.intervalHours(),start,start.plus(Duration.ofDays(p.durationDays())));save(key,"MEDICATION_PLAN",payload);}
 private void save(String key,String target,Object value){try{outbox.save(new OutboxEvent(key,target,mapper.writeValueAsString(value)));}catch(Exception e){throw new IllegalStateException("Could not write reliable notification event",e);}}
 private record EventPayload(String eventId,String type,UUID appointmentId,UUID patientId,String patientEmail,String patientName,UUID doctorUserId,String doctorEmail,String doctorName,OffsetDateTime startAt,int durationMinutes,String message){}
 private record MedicationPayload(String eventId,UUID userId,String email,UUID appointmentId,String medication,String instructions,int intervalHours,Instant startAt,Instant endAt){}
}
